(* open Types *)
(* open Messages *)

(* class fake msg: ['a] writer = *)
(*   object *)
(*     method private read = *)
(*       user_error "cannot read files%s" msg *)
(*     method private write _ = *)
(*       user_error "cannot write files%s" msg *)
(*     method private write_svg _ = *)
(*       user_error "cannot write SVG files%s" msg *)
(*     method private write_pdf _ = *)
(*       user_error "cannot write PDF files%s" msg *)
(*   end *)
